#!/usr/bin/with-contenv bash
# Installs the Sonarr Metadata Proxy CA into the container trust store so that
# .NET (which backs Sonarr) trusts the proxy certificate for skyhook.sonarr.tv.
#
# This runs once at container start (LinuxServer /custom-cont-init.d hook).
# The CA file is generated by the proxy and shared through the "certs" volume.

set -e

CA_SOURCE="/shared/certs/ca.crt"
CA_DEST="/usr/local/share/ca-certificates/sonarr-metadata-proxy-ca.crt"

if [ ! -f "${CA_SOURCE}" ]; then
  echo "[sonarr-metadata-proxy] CA not present yet at ${CA_SOURCE}; skipping install."
  exit 0
fi

echo "[sonarr-metadata-proxy] Installing proxied CA for skyhook.sonarr.tv"
cp "${CA_SOURCE}" "${CA_DEST}"
update-ca-certificates 2>/dev/null || true

echo "[sonarr-metadata-proxy] CA installed."